### ISSUE TITLE
stablediffusion tensorrt demo error

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/diffusers#3874]
I got this error:

UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported.

when runing the trt pipe line demo.

```
pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    custom_pipeline="stable_diffusion_tensorrt_txt2img",
    # revision="fp16",
    torch_dtype=torch.float16,
    scheduler=scheduler,
)

# re-use cached folder to save ONNX models and TensorRT Engines
cache_dir = os.path.basename(model_id) + '_cached_trt'
os.makedirs(cache_dir, exist_ok=True)
print(f'cached dir: {cache_dir}')
pipe.set_cached_folder(
    cache_dir,
    revision="fp16",
)

pipe = pipe.to("cuda")

prompt = "a beautiful photograph of Mt. Fuji during cherry blossom"
image = pipe(prompt).images[0]
image.save("tensorrt_mt_fuji.png")
```

what could I do to resolve this? Happened only on stablediffusion 2.1 model.

**Comment by patrickvonplaten** [comment]
Gentle ping to @asfiyab-nvidia here

**Comment by henbucuoshanghai** [comment]
safertensor  2 onnx  and to tensorrt?
have u solved it?

**Comment by JiaojiaoYe1994** [comment]
Hi, I have met the same issue, have you solved this problem?

**Comment by asfiyab-nvidia** [comment]
This error is caused due to the following issue: https://github.com/pytorch/pytorch/issues/97262
It has been fixed in the latest release of Torch. Please upgrade your torch version!

**Comment by jfischoff** [comment]
@asfiyab-nvidia I'm still getting this error with the pytorch nightly. I changed the opset to 18 as well. Is there anything else I need to do to get around this issue?
