### ISSUE TITLE
Out painting

### ISSUE THREAD

**Issue by wodsoe** [huggingface/diffusers#438]
Is there outpainting example?

**Comment by rashmimarganiatgithub** [comment]
unfortunately, there is no outpainting for now. But can be expected very soon.

**Comment by allo-** [comment]
At least using the inpating or img2img pipelines it doesn't seem to work without at least sketching what you want to have in the outpainted parts (and you often still have hard lines on the boundary of the original image).

**Comment by leszekhanusz** [comment]
@allo- 

It's because of this bug: #261 and is fixed by applying the recommended fix.

**Comment by leszekhanusz** [comment]
@allo- I made the PR #469 to fix the boundary problem

**Comment by allo-** [comment]
Outpainting still doesn't seem to work for me. A black boundary with a mask stays black with 1.0 and 0.1 and fades into the image with values like 0.8.

**Comment by patrickvonplaten** [comment]
@patil-suraj and/or @anton-l could you check this?

**Comment by patil-suraj** [comment]
Hi! Outpainting can be implemented using the new `StableDiffusionInpaintingPipeline` and the inpainting model https://huggingface.co/runwayml/stable-diffusion-inpainting. We don't have an example in diffusers at the moment but you can checkout the code for the stable diffusion infinity space which does outpainting https://huggingface.co/spaces/lnyan/stablediffusion-infinity/blob/main/app.py

**Comment by patrickvonplaten** [comment]
This space is also quite fun: https://huggingface.co/spaces/huggingface-projects/stable-diffusion-multiplayer

**Comment by leszekhanusz** [comment]
> This space is also quite fun: https://huggingface.co/spaces/huggingface-projects/stable-diffusion-multiplayer

It returns 404

**Comment by patrickvonplaten** [comment]
Ah sorry - I think it's still in development :sweat_smile: It'll be public very soon!
