### ISSUE TITLE
The `train_dataloader` was not passed into `acceler.prepare()`.

### ISSUE THREAD

**Issue by linhduongtuan** [huggingface/diffusers#4991]
### Describe the bug

Hi @sayakpaul,
I encountered a bug in the file located in the folder examples/t2i_adapter/train_t2i_adapter_sdxl.py. At line 1067 of the file, it seems to be a bug if you leave it as follows:

t2iadapter, optimizer, lr_scheduler = accelerator.prepare(t2iadapter, optimizer, lr_scheduler)

It should be fine if you define it like this:
t2iadapter, optimizer, lr_scheduler, train_dataloader = accelerator.prepare(t2iadapter, optimizer, lr_scheduler, train_dataloader)

Please confirm this issue.

Thanks,
Linh

### Reproduction

t2iadapter, optimizer, lr_scheduler = accelerator.prepare(t2iadapter, optimizer, lr_scheduler)

### System Info

Ubuntu 20.4

### Who can help?

Hi @sayakpaul

**Comment by linhduongtuan** [comment]
It also has a problem loading the second prompt image. If you do not use the second prompt image, I can finetune, but I encounter an error at line 118 of train_t2i_adapter_sdxl.py.

**Comment by sayakpaul** [comment]
Cc: @sayakpaul

**Comment by patrickvonplaten** [comment]
Think this should be fixed with: https://github.com/huggingface/diffusers/pull/5001 no?

**Comment by linhduongtuan** [comment]
Thank you @patrickvonplaten for your swift support. I will try it again.

**Comment by linhduongtuan** [comment]
Hi @patrickvonplaten,
An error is still raised when calling the second validation image with the argument `--validation_image` like this: "train_t2i_adapter_sdxl.py: error: unrecognized arguments: ./conditioning_image_2.png."

Thank in advance.
Linh
