### ISSUE TITLE
Loading ex. Würstchen: AttributeError: 'Linear' object has no attribute 'lora_layer'

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#5524]
### Describe the bug

Loading "other" models like Wüerstchen worked fine before, but now an error is raised: 
`AttributeError: 'Linear' object has no attribute 'lora_layer'`

### Reproduction

```
from diffusers import AutoPipelineForText2Image
from diffusers.pipelines.wuerstchen import DEFAULT_STAGE_C_TIMESTEPS
pipe = AutoPipelineForText2Image.from_pretrained("warp-ai/wuerstchen", torch_dtype=torch.float16)
```

### Logs

```shell
Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 2646, in execute
    pipe = AutoPipelineForText2Image.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\auto_pipeline.py", line 331, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1269, in from_pretrained
    connected_pipes = {
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1270, in <dictcomp>
    prefix: DiffusionPipeline.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1206, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 470, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 786, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 62, in __init__
    self.set_default_attn_processor()
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 140, in set_default_attn_processor
    self.set_attn_processor(processor, _remove_lora=True)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 124, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 116, in fn_recursive_attn_processor
    module.set_processor(processor, _remove_lora=_remove_lora)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\attention_processor.py", line 319, in set_processor
    if hasattr(self, "processor") and _remove_lora and self.to_q.lora_layer is not None:
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'lora_layer'
```

### System Info

Win 11

### Who can help?

 @sayakpaul

**Comment by sayakpaul** [comment]
No problems here:
https://colab.research.google.com/gist/sayakpaul/0ad1e34d4f96b10addf98fa7dd3298a6/scratchpad.ipynb

**Comment by tin2tin** [comment]
Maybe it could be trickered by having previous loaded LoRAs in memory and then import Würstchen? 

Here's the full stdout:

```
Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 2646, in execute
    pipe = AutoPipelineForText2Image.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\auto_pipeline.py", line 331, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1269, in from_pretrained
    connected_pipes = {
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1270, in <dictcomp>
    prefix: DiffusionPipeline.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1206, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 470, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 786, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 62, in __init__
    self.set_default_attn_processor()
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 140, in set_default_attn_processor
    self.set_attn_processor(processor, _remove_lora=True)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 124, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 116, in fn_recursive_attn_processor
    module.set_processor(processor, _remove_lora=_remove_lora)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\attention_processor.py", line 319, in set_processor
    if hasattr(self, "processor") and _remove_lora and self.to_q.lora_layer is not None:
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'lora_layer'
Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 2646, in execute
    pipe = AutoPipelineForText2Image.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\auto_pipeline.py", line 331, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1269, in from_pretrained
    connected_pipes = {
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1270, in <dictcomp>
    prefix: DiffusionPipeline.from_pretrained(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1206, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 470, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 786, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 62, in __init__
    self.set_default_attn_processor()
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 140, in set_default_attn_processor
    self.set_attn_processor(processor, _remove_lora=True)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 124, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\modeling_wuerstchen_prior.py", line 116, in fn_recursive_attn_processor
    module.set_processor(processor, _remove_lora=_remove_lora)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\models\attention_processor.py", line 319, in set_processor
    if hasattr(self, "processor") and _remove_lora and self.to_q.lora_layer is not None:
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'lora_layer'
```

**Comment by sayakpaul** [comment]
I need the full snippet for that. I guess you didn't provide a full snippet in the description here: https://github.com/huggingface/diffusers/issues/5524#issue-1961211770.

**Comment by tin2tin** [comment]
![wuerst](https://github.com/huggingface/diffusers/assets/1322593/aa3a2f00-9204-424f-924c-c43d336288b8)

**Comment by sayakpaul** [comment]
I am sorry but I couldn't reproduce it as you can see in the Colab I posted. We need something that we can fully reproduce otherwise we cannot do much.

**Comment by tin2tin** [comment]
Maybe the snippet needs to run locally to provoke the error? 

Could it be the torch version? What torch version does the latest Diffusers need?

**Comment by sayakpaul** [comment]
I ran it from a VM too, and it was fine. 

I am using Torch 2.1.

**Comment by tin2tin** [comment]
Updating Torch didn't solve it. 

I'm out of ideas. 

So, I guess, I'll have to disable Würstchen in Pallaidium, until someone else will encounter this bug and do something about it.

**Comment by tin2tin** [comment]
AutoPipelineForText2Image/AutoPipelineForImage2Image is also used in relation to this bug - maybe there are some funky settings/paths handling in this pipeline? https://github.com/huggingface/diffusers/issues/5578

**Comment by sayakpaul** [comment]
It really seems to be a Windows-specific problem. I couldn't reproduce it on any UNIX-based system.

**Comment by okotaku** [comment]
@sayakpaul @tin2tin 
I encountered the error with the installed peft environment.

```
➜  /workspace git:(main) ✗ pip install peft
➜  /workspace git:(main) ✗ python          
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from diffusers.pipelines.wuerstchen import DEFAULT_STAGE_C_TIMESTEPS, WuerstchenPrior
>>> WuerstchenPrior.from_pretrained("warp-ai/wuerstchen-prior", subfolder="prior")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 787, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 644, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 62, in __init__
    self.set_default_attn_processor()
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 140, in set_default_attn_processor
    self.set_attn_processor(processor, _remove_lora=True)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 124, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 121, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py", line 116, in fn_recursive_attn_processor
    module.set_processor(processor, _remove_lora=_remove_lora)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 381, in set_processor
    if hasattr(self, "processor") and _remove_lora and self.to_q.lora_layer is not None:
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'lora_layer'
```

**Comment by tin2tin** [comment]
@okotaku I can confirm, that this is related to peft. Uninstalling it, makes Wüerstchen work again.

**Comment by patrickvonplaten** [comment]
The problem here is that PEFT is installed and we don't have super good support for PEFT yet.

**Comment by okotaku** [comment]
@tin2tin This issue may be solved in diffusers==0.22.3. Please check it.

**Comment by tin2tin** [comment]
@okotaku Yes, that has been solved. Thank you!

**Comment by YunfanZhang42** [comment]
Using `torch==2.1.0`, `diffusers==0.23.0` and `peft==0.6.2` on Linux, I can still reproduce this problem. Uninstalling peft fixed the error for me. May be the peft integrations still worth another look? @patrickvonplaten @okotaku @sayakpaul

**Comment by Amal-Baby-Mathews** [comment]
Anyone who found this issue while searching for the same issue for autotrain-advanced, installing autotrain-advanced==0.7.5 version worked for me.
