### ISSUE TITLE
Usage of init_git_repo is not very clear

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#81]
init_git_repo expects some arguments which are not very clear (e.g. you need to pass `local_rank` which is not very obvious when the functions is creating a git repo).

cc @anton-l

**Comment by patrickvonplaten** [comment]
@anton-l - what do you think here?

**Comment by anton-l** [comment]
@osanseviero very much agree with you here, this is mostly a legacy of transformers code. @patrickvonplaten I've now added default values for these args, so that our training notebook doesn't rely on them, but the code needs a major cleanup still.

I see a couple of ways we can improve it:
* add a `TrainingArguments` class of our own, with default values for hub-related variables.
* try to rewrite `init_git_repo` and `push_to_hub` to use as little non-essential info as possible, but that will either reduce flexibility, or significantly increase the number of arguments to pass.
* longer term solution: offload this logic to `huggingface_hub` and somehow retrieve all of the needed variables there.

Thoughts?

**Comment by osanseviero** [comment]
Just suggestions from an outsider of the codebase (cc @LysandreJik as well on this)

* To add a `TrainngArguments` class to define how the Hub-behaviour should be 👍 
* `push_to_hub` should not accept `args` as a first argument tbh. Essential args such as `hub_model_id`, `dataset`, etc should be passed as explicit params instead. I find it strange that the `Repository` is passed to `push_to_hub`. A nicer interface for me would be something like this (assuming non-git-based method)

```python
def push_to_hub(
    pipeline: DiffusionPipeline,
    repo_id: str,
    commit_message: Optional[str] = "End of training",
    blocking: bool = True,
    private: Optional[bool] = None,
    token: Optional[str] = None,
    **kwargs,
) 
```

**Comment by patrickvonplaten** [comment]
Agree with @osanseviero here mostly

**Comment by patrickvonplaten** [comment]
I think we've mentioned a couple of times to remove the `init_git_repo` functionality from the unconditional training script. Also see: https://github.com/huggingface/diffusers/pull/266#discussion_r960542231

@anton-l could you please adapt the unconditional training script accordingly?

**Comment by patrickvonplaten** [comment]
@anton-l this is still not changed: https://github.com/huggingface/diffusers/blob/1d04e1b4deb1bdebabd9a94163ea5567e54c6ada/examples/unconditional_image_generation/train_unconditional.py#L12

Could you please take 5min to change it as discussed?

**Comment by anton-l** [comment]
Addressed in https://github.com/huggingface/diffusers/pull/1022

**Comment by murphyk** [comment]
The same problem persists in /github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb
(see duplicate issue https://github.com/huggingface/diffusers/issues/1922)
