### ISSUE TITLE
convert_diffusers_to_original_sdxl.py doesn't work anymore

### ISSUE THREAD

**Issue by zyddnys** [huggingface/diffusers#8805]
### Describe the bug

Nowadays models are saved as `diffusion_pytorch_model-00001-of-00002.safetensors` and `diffusion_pytorch_model-00002-of-00002.safetensors` instead of a single `diffusion_pytorch_model.safetensors`
This causes convert_diffusers_to_original_sdxl.py to generate file not found error
```
FileNotFoundError: [Errno 2] No such file or directory: 'output/XXX/unet/diffusion_pytorch_model.bin'
```

### Reproduction

python convert_diffusers_to_original_sdxl.py --model_path output/XXX/  --checkpoint XXX.safetensors --use_safetensors

### System Info

diffusers=0.29.2

**Comment by DN6** [comment]
cc: @sayakpaul

**Comment by pljj315** [comment]
meet this issue too

**Comment by pljj315** [comment]
I solve this issue by adding these line : 
![image](https://github.com/huggingface/diffusers/assets/85743914/89755902-7ac6-4694-bd5d-ce4a1d325b3e)

# Load models from safetensors if it exists, if it doesn't pytorch
    if osp.exists(unet_path):
        unet_state_dict = load_file(unet_path, device="cpu")
    ###  modify:
    elif osp.exists(osp.join(args.model_path, "unet", "diffusion_pytorch_model.safetensors.index.json")):
        dict_list = glob.glob((args.model_path + "/" +"unet" + "/*.safetensors"))
        unet_state_dict = {}
        for dict_path in dict_list:
            part_dict = {}
            with safe_open(dict_path, framework="pt", device="cpu") as f:
                for k in f.keys():
                    part_dict[k] = f.get_tensor(k)
            unet_state_dict.update(part_dict)
    else:
        unet_path = osp.join(args.model_path, "unet", "diffusion_pytorch_model.bin")
        unet_state_dict = torch.load(unet_path, map_location="cpu")

**Comment by sayakpaul** [comment]
Thanks for reporting. Would you be able to open a PR for this now that you have a solution too? Please also provide a full reproducible example that we can verify on our end to confirm that the fix is working.

**Comment by Naylenv** [comment]
meet this issue too

**Comment by jslegers** [comment]
Possibly same issue as 8974?

**Comment by a-r-r-o-w** [comment]
I am marking this as closed in favor of the more recent #8974. For a very short period, variant loading was broken which may have resulted in problems, but should be fixed now (cc @sayakpaul @DN6)

**Comment by TheGoddessFiles** [comment]
> I am marking this as closed in favor of the more recent [#8974](https://github.com/huggingface/diffusers/issues/8974). For a very short period, variant loading was broken which may have resulted in problems, but should be fixed now (cc [@sayakpaul](https://github.com/sayakpaul) [@DN6](https://github.com/DN6))

I am for some reason still having an issue with this? Mind you i'm still a bit new to this, so some of this I'm learning still but I continue to get the same issue for seemingly the same reason as OP and I really don't know how to go about fixing it because no amount of research has brought me to a fix that has worked (or that I know how to employ)

**Comment by sayakpaul** [comment]
Do you have a fully reproducible snippet?
